Repository nasa/OnAIR, pull requests merged in 2023-09, with the labels that each got.

#30 Enhanced error handling and design of parse_data
  onair/src/run_scripts/execution_engine.py
  test/src/run_scripts/test_execution_engine.py
Labels: bug

#36 24 allow for dynamic plugins
  driver.py
  onair/config/default_config.ini
  onair/src/data_driven_components/ai_plugin_abstract/__init__.py
  onair/src/data_driven_components/ai_plugin_abstract/core.py
  onair/src/data_driven_components/data_driven_learning.py
  onair/src/data_driven_components/kalman/__init__.py
  onair/src/reasoning/agent.py
  onair/src/run_scripts/execution_engine.py
  onair/src/run_scripts/sim.py
  plugins/generic/__init__.py
  plugins/generic/generic_plugin.py
  plugins/kalman_plugin/__init__.py
  plugins/kalman_plugin/kalman_plugin.py
  test/onair/data_handling/__init__.py
  test/onair/data_handling/parsers/__init__.py
  test/onair/data_handling/parsers/test_csv_parser.py
  test/onair/data_handling/parsers/test_forty_two_parser.py
  test/onair/data_handling/parsers/test_on_air_parser.py
  test/onair/data_handling/parsers/test_parser_util.py
  test/onair/data_handling/parsers/test_tlm_json_parser.py
  test/onair/data_handling/test_data_source.py
  test/onair/data_handling/test_time_synchronizer.py
  test/onair/src/data_driven_components/ai_plugin_abstract/test_core.py
  test/onair/src/data_driven_components/test_data_driven_learning.py
  test/onair/src/reasoning/test_agent.py
  test/onair/src/reasoning/test_diagnosis.py
  test/onair/src/run_scripts/test_execution_engine.py
  test/onair/src/run_scripts/test_sbn_adapter.py
  test/onair/src/run_scripts/test_sim.py
  test/onair/src/systems/test_status.py
  test/onair/src/systems/test_telemetry_test_suite.py
  test/onair/src/systems/test_vehicle_rep.py
  test/onair/src/util/test_cleanup.py
  test/onair/src/util/test_data_conversion.py
  test/onair/src/util/test_file_io.py
  test/onair/src/util/test_print_io.py
  test/onair/src/util/test_sim_io.py
  test/onair/utils/test_tlm_json_converter.py
  test/plugins/generic/test_generic_plugin.py
  test/plugins/kalman/test_kalman_plugin.py
Labels: enhancement

#41 Changes for fixing testing of ast.parse
  onair/src/run_scripts/execution_engine.py
  test/onair/src/run_scripts/test_execution_engine.py
Labels: unit test
